version: '3.8'

services:
  app:
    image: node:20 # Change this line to use Node.js 16 or higher
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - .:/app
    command: npm run start:dev
    environment:
      MONGO_URI: 'mongodb+srv://venwiz-mvp-dev2:WtsVS0f4clVFtGIk@cluster2.vs2kj.mongodb.net/vendor-profile?retryWrites=true&w=majority'
      RABBITMQ_URI: 'amqp://guest:guest@rabbitmq:5672'
      PORT: '3000'
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
